[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "farfetch"
authors = [{name = "Nic Annau", email = "nicannau@gmail.com"}]
dynamic = ["version", "description"]
